AWSTemplateFormatVersion: "2010-09-09"
Description: 'Simple S3 bucket for testing PR validation'

Parameters:
  Environment:
    Type:  String
    Default:  test
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment name

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "my-s3-bucket-${Environment}-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Environment
          Value:  !Ref Environment
        - Key: Environment
          Value: GithubActionsTesting

Outputs:
  BucketName:
    Description: Name of the created S3 bucket
    Value: !Ref S3Bucket